[package]
name = "rust-futures"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
bytes = "1.7.1"
log = { version = "0.4.22", features = [] }
mini-redis = "0.4.1"
simple_logger = "5.0.0"
tokio = { version = "1.40.0", features = ["full"] }
